name: kunit-build

on:
  workflow_call:
    inputs:
      commit_url:
        type: string
        required: true
        description: |
          内核源码仓库commit链接, 如: 
            - https://github.com/RVCK-Project/rvck/commit/32c7ba2136024ee1563416607e3265ccbee6a55e
            - https://github.com/RVCK-Project/rvck-olk/pull/103
      
      upload_dir:
        type: string
        required: true
        description: '上传目录'

    outputs:
      kernel_download_url:
        value: ${{ jobs.kernel-build.outputs.kernel_download_url }}
      initramfs_download_url:
        value: ${{ jobs.kernel-build.outputs.initramfs_download_url }}
      kernel_md5sum:
        value: ${{ jobs.kernel-build.outputs.kernel_md5sum }}
      initramfs_md5sum:
        value: ${{ jobs.kernel-build.outputs.initramfs_md5sum }}
      summary_content:
        value: ${{ jobs.kernel-build.outputs.summary_content }}
    
    secrets:
      rync_passphrase: 
        required: true
        description: 'rsync上传内核所需密码'

jobs:
  kernel-build:
    runs-on:
      group: kernel_build-runner
            
    outputs:
      kernel_download_url: ${{ steps.publish-kernel.outputs.kernel_download_url }}
      initramfs_download_url: ${{ steps.publish-kernel.outputs.initramfs_download_url }}
      kernel_md5sum: ${{ steps.publish-kernel.outputs.kernel_md5sum }}
      initramfs_md5sum: ${{ steps.publish-kernel.outputs.initramfs_md5sum }}
      summary_content: ${{ steps.summary.outputs.summary_content }}

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      kernel_result_dir: guix_result

    steps:
      - name: clean ws
        run: |
          sudo rm -rf ./* || true

      - name: binfmt_misc mount before setup qemu
        run: ls -alh /proc/sys/fs/binfmt_misc

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3      

      - name: kernel-build
        run: |
          
          mkdir -p "${kernel_result_dir}"
          docker run --privileged \
            -v "$(pwd)/${kernel_result_dir}:/srv/guix_result" \
            hub.oepkgs.net/oerv-ci/guix-kernel-cross-build:v15 \
            guix-cross-build ${{ inputs.commit_url }}
   
      - name: publish kernel
        id: publish-kernel
        env:
          RSYNC_PASSWORD: ${{ secrets.rync_passphrase }}
        run: |
          
          rsync -av --progress --mkpath "${kernel_result_dir}"/*/* rvck@10.30.190.110::RVCK/${{ inputs.upload_dir }}/
          echo "kernel_download_url=https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/${{ inputs.upload_dir }}/Image" >> $GITHUB_OUTPUT
          echo "kernel_md5sum=$(awk '{print $1}' "${kernel_result_dir}"/*/Image.md5sum)" >> $GITHUB_OUTPUT
          echo "initramfs_download_url=https://repo.tarsier-infra.isrc.ac.cn/openEuler-RISC-V/RVCK/OERV-RVCI/${{ inputs.upload_dir }}/initramfs.img" >> $GITHUB_OUTPUT
          echo "initramfs_md5sum=$(awk '{print $1}' "${kernel_result_dir}"/*/initramfs.img.md5sum)" >> $GITHUB_OUTPUT
      
      - name: summary
        if: ${{ always() }}
        id: summary
        env:
          kernel_url: ${{ steps.publish-kernel.outputs.kernel_download_url }}
          upload_dir: ${{ inputs.upload_dir }}
        continue-on-error: true
        run: |
          if [ "$kernel_url" != "" ]; then
            result="Kernel build succeeded: [${upload_dir}]($(dirname ${kernel_url}))/"
          else
            result="Kernel build failed."
          fi

          cat > summary << EEE
          ## Kernel Build Result
          
          $result
          
          $(cat "${kernel_result_dir}"/*/*.md5sum)

          EEE

          cat summary > $GITHUB_STEP_SUMMARY
          
          echo "summary_content<<EOF" >> $GITHUB_OUTPUT
          cat summary >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

