name: update status

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
        description: 仓库
      event_id:
        type: string
        required: true
        description: 'pr|issue|comment id'
      event_name:
        required: true
        type: string
        description: '事件类型, pr|issue|comment'
      append_content:
        type: string
        description: '追加内容'
    secrets:
      gh_token:
        required: true

env:
  GH_TOKEN: ${{ secrets.gh_token }}
  GH_REPO: ${{ inputs.repo }}
  event_id: ${{ inputs.event_id }}
  event_name: ${{ inputs.event_name }}
  append_conent: ${{ inputs.append_content }}

jobs:
  update-status:
    runs-on: 'ubuntu-latest'
    steps:
      - name: show-info
        run: |
          cat > $GITHUB_STEP_SUMMARY << EEE
          | input | value |
          |:-:|:-:|
          |repo| $GH_REPO |
          |event name |$event_name |
          |event id |$event_id |
          |append_content | $append_conent |
          EEE
      - name: issue_comment
        if: ${{ env.event_name == 'issue_comment' }}
        run: |
         echo todo
      - name: pr|issue
        if: ${{ env.event_name == 'issues' || env.event_name == 'pull_request_target' }}
        run: |
          content=$(gh issue view "$event_id" --json body  -q '.body')
          new_content=$(cat <<EEE
          $content
          $append_content
          EEE
          )
          echo $new_content
          gh issue edit "$event_id" -b "$new_content"
